// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxmJphbGi_WR5X34aLwZLDfETlten9g2k',
    appId: '1:664213996833:web:bcd720fb0a84f1630e2a60',
    messagingSenderId: '664213996833',
    projectId: 'flutter-questions-app',
    authDomain: 'flutter-questions-app.firebaseapp.com',
    storageBucket: 'flutter-questions-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl2OSEjWMgmA0dQaWAQ2j-XK1hf35KY9o',
    appId: '1:664213996833:android:80e99e378d963aa50e2a60',
    messagingSenderId: '664213996833',
    projectId: 'flutter-questions-app',
    storageBucket: 'flutter-questions-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0qrr-78nnYeNnbZh1_BYqxy1X7lLOst4',
    appId: '1:664213996833:ios:17fa84c3c1bb5b6d0e2a60',
    messagingSenderId: '664213996833',
    projectId: 'flutter-questions-app',
    storageBucket: 'flutter-questions-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterQuestionsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0qrr-78nnYeNnbZh1_BYqxy1X7lLOst4',
    appId: '1:664213996833:ios:17fa84c3c1bb5b6d0e2a60',
    messagingSenderId: '664213996833',
    projectId: 'flutter-questions-app',
    storageBucket: 'flutter-questions-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterQuestionsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxmJphbGi_WR5X34aLwZLDfETlten9g2k',
    appId: '1:664213996833:web:7e0de29dc31e58d10e2a60',
    messagingSenderId: '664213996833',
    projectId: 'flutter-questions-app',
    authDomain: 'flutter-questions-app.firebaseapp.com',
    storageBucket: 'flutter-questions-app.firebasestorage.app',
  );
}
